firebolt-db/jdbc

build.gradle, src/main/java/com/firebolt/jdbc/metadata/FireboltDatabaseMetadata.java, src/main/java/com/firebolt/jdbc/resultset/FireboltResultSet.java, src/main/java/com/firebolt/jdbc/resultset/FireboltResultSetMetaData.java, src/main/java/com/firebolt/jdbc/type/BaseType.java, src/main/java/com/firebolt/jdbc/type/FireboltDataType.java, src/test/java/com/firebolt/jdbc/metadata/FireboltDatabaseMetadataTest.java, src/test/java/com/firebolt/jdbc/resultset/FireboltResultSetTest.java, src/test/resources/responses/firebolt-response-with-bytea, src/test/resources/responses/metadata/expected-types, src/testCommon/java/com/firebolt/jdbc/testutils/AssertionUtil.java
Add support for bytea in HEX format
=> Add support for bytea in HEX format

.github/workflows/build.yml, .github/workflows/code-analysis.yml, .github/workflows/release.yml
TODO: decide what to do with javadoc release wf
=> ci: version split

.github/workflows/code-analysis.yml, .github/workflows/integration-test.yml, build.gradle
This allows us to see test execution and performance over time in Foresight.
=> ci: Add foresight test telemetry

src/main/java/com/firebolt/jdbc/client/query/StatementClientImpl.java, src/main/java/com/firebolt/jdbc/connection/settings/FireboltProperties.java, src/main/java/com/firebolt/jdbc/metadata/FireboltDatabaseMetadata.java, src/main/java/com/firebolt/jdbc/statement/FireboltStatement.java, src/test/java/com/firebolt/jdbc/client/query/StatementClientImplTest.java, src/test/java/com/firebolt/jdbc/connection/settings/FireboltPropertiesTest.java, src/test/java/com/firebolt/jdbc/statement/FireboltStatementTest.java
Drop support for non-standard sql and aggressive cancel
=> Drop support for non-standard sql and aggressive cancel

src/main/java/com/firebolt/jdbc/connection/FireboltConnection.java, src/main/java/com/firebolt/jdbc/metadata/FireboltDatabaseMetadata.java, src/main/java/com/firebolt/jdbc/metadata/MetadataColumns.java, src/test/java/com/firebolt/jdbc/metadata/FireboltDatabaseMetadataTest.java
=> Metadata fixes

src/integrationTest/java/integration/tests/PreparedStatementArrayTest.java, src/integrationTest/resources/statements/prepared-statement-array/cleanup.sql, src/integrationTest/resources/statements/prepared-statement-array/ddl.sql, src/test/java/com/firebolt/jdbc/resultset/FireboltResultSetTest.java, src/test/resources/responses/firebolt-response-with-array
This PR just adds tests that validate that int arrays works well. This is to be sure that FIR-5579 can be safely closed.
=> FIR-5579 added tests for int array. Tests of other arrays TBD

.github/workflows/integration-test.yml
Update integration testing workflow to use a new setup action v2, which creates new identity engines and databases
=> ci: new identity

.github/workflows/release.yml
=> ci: Use published for publishing

src/integrationTest/java/integration/tests/StatementTest.java, src/main/java/com/firebolt/jdbc/resultset/FieldTypeConverter.java, src/main/java/com/firebolt/jdbc/type/BaseType.java, src/test/java/com/firebolt/jdbc/resultset/FireboltResultSetTest.java, src/test/resources/responses/firebolt-response-with-infinity
Also added conversion from int floating point types
=> FIR-26736 improved support of infinity

src/integrationTest/java/integration/tests/StatementTest.java
Actually the validation was already implemented: ddProperty() calls validateConnection() that in turn calls select 1
=> FIR-29701: validation of set parameters

gradle.properties, src/main/java/com/firebolt/jdbc/util/VersionUtil.java, src/test/java/com/firebolt/jdbc/metadata/FireboltDatabaseMetadataTest.java, src/test/java/com/firebolt/jdbc/util/VersionUtilTest.java
also added tests that validates (unsuccessful) connection without account
=> starting version 3.0.3-snapshot

src/integrationTest/java/integration/tests/ConnectionTest.java, src/main/java/com/firebolt/jdbc/connection/FireboltConnectionServiceSecret.java, src/main/java/com/firebolt/jdbc/connection/FireboltConnectionUserPassword.java, src/main/java/com/firebolt/jdbc/service/FireboltEngineVersion2Service.java, src/test/java/com/firebolt/jdbc/connection/FireboltConnectionServiceSecretTest.java, src/test/java/com/firebolt/jdbc/connection/FireboltConnectionUserPasswordTest.java, src/test/java/com/firebolt/jdbc/service/FireboltEngineVersion2ServiceTest.java
also added tests that validates (unsuccessful) connection without account
=> FIR-30506: fixed connection without DB

src/integrationTest/java/integration/tests/StatementTest.java, src/main/java/com/firebolt/jdbc/connection/FireboltConnection.java, src/main/java/com/firebolt/jdbc/connection/FireboltConnectionServiceSecret.java, src/main/java/com/firebolt/jdbc/connection/settings/FireboltProperties.java, src/main/java/com/firebolt/jdbc/type/JavaTypeToFireboltSQLString.java, src/test/java/com/firebolt/jdbc/client/query/StatementClientImplTest.java, src/test/java/com/firebolt/jdbc/connection/settings/FireboltPropertiesTest.java, src/test/java/com/firebolt/jdbc/statement/FireboltStatementTest.java, src/test/java/com/firebolt/jdbc/type/JavaTypeToFireboltSQLStringTest.java
also changed escaping of single quote from backslahing to quote doubling to make tests to work
=> FIR-31064: fixed lost initial connection options

src/main/java/com/firebolt/jdbc/statement/preparedstatement/FireboltPreparedStatement.java, src/main/java/com/firebolt/jdbc/type/JavaTypeToFireboltSQLString.java, src/test/java/com/firebolt/jdbc/statement/preparedstatement/FireboltPreparedStatementTest.java, src/test/java/com/firebolt/jdbc/type/JavaTypeToFireboltSQLStringTest.java
also added more tests of prepared statement
=> FIR-32019: PreparedStatement.setObject with all parameters

src/integrationTest/java/integration/tests/PreparedStatementTest.java, src/integrationTest/resources/statements/prepared-statement/ddl.sql, src/main/java/com/firebolt/jdbc/statement/preparedstatement/FireboltPreparedStatement.java, src/main/java/com/firebolt/jdbc/type/JavaTypeToFireboltSQLString.java, src/test/java/com/firebolt/jdbc/statement/preparedstatement/FireboltPreparedStatementTest.java
=> FIR-32015: implemented missing trivial setters in PreparedStatement

src/integrationTest/java/integration/tests/PreparedStatementTest.java, src/integrationTest/resources/statements/prepared-statement/ddl.sql, src/main/java/com/firebolt/jdbc/statement/preparedstatement/FireboltPreparedStatement.java, src/main/java/com/firebolt/jdbc/type/JavaTypeToFireboltSQLString.java, src/main/java/com/firebolt/jdbc/type/date/SqlDateUtil.java, src/test/java/com/firebolt/jdbc/statement/preparedstatement/FireboltPreparedStatementTest.java, src/test/java/com/firebolt/jdbc/type/JavaTypeToFireboltSQLStringTest.java
also added simple setTime() as a pair to the ResultSet.getTime()
=> FIR-32017: PreparedStatement: set date/time/timestamp with calendar

src/main/java/com/firebolt/FireboltDriver.java, src/main/java/com/firebolt/jdbc/GenericWrapper.java, src/main/java/com/firebolt/jdbc/JdbcBase.java, src/main/java/com/firebolt/jdbc/client/account/FireboltAccount.java, src/main/java/com/firebolt/jdbc/metadata/FireboltDatabaseMetadata.java, src/main/java/com/firebolt/jdbc/resultset/FireboltResultSet.java, src/main/java/com/firebolt/jdbc/resultset/FireboltResultSetMetaData.java, src/main/java/com/firebolt/jdbc/statement/ParamMarker.java, src/main/java/com/firebolt/jdbc/statement/StatementUtil.java, src/main/java/com/firebolt/jdbc/statement/preparedstatement/FireboltPreparedStatement.java, src/main/java/com/firebolt/jdbc/statement/rawstatement/QueryRawStatement.java, src/main/java/com/firebolt/jdbc/type/BaseType.java, src/main/java/com/firebolt/jdbc/type/FireboltDataType.java, src/main/java/com/firebolt/jdbc/type/FireboltDataTypeDisplayNames.java, src/main/java/com/firebolt/jdbc/type/JavaTypeToFireboltSQLString.java, src/main/java/com/firebolt/jdbc/util/LoggerUtil.java, src/main/java/com/firebolt/jdbc/util/VersionUtil.java
* removed redundant throws SQLException
* removed redundant code
* added some `@SuppressWarnings`
* extracted `GenericWrapper` from `JdbcBase` and used it
* minor warnings
=> FIR-32120: removed redundant throws declarations and fixed some warnings

build.gradle
Migrated from quilt to yumi licenser, as quilt is deprecated
=> build: migrate to yumi licenser

gradle.properties
=> build: reduce version

src/test/java/com/firebolt/jdbc/metadata/FireboltDatabaseMetadataTest.java, src/test/java/com/firebolt/jdbc/util/VersionUtilTest.java
Fixed version related unit tests
=> test: fix unit tests

build.gradle
Removed redundant licenser plugin
=> build: remove redundant plugin

build.gradle
Added artifact signing to gradle build
=> build: add artifact signing

.github/workflows/release.yml
Added missing gradle signing secrets
=> ci: add missing secrets

.github/workflows/build.yml, .github/workflows/performance-test.yml
This prevents download action from downloading it.
=> ci: Bump upload artifact action version

src/test/java/com/firebolt/jdbc/client/UserAgentFormatter.java
This test is fairly useless as we're testing the same logic as we're testing against but at least we can run it locally now.
=> test: Fix unit tests when run locally from Mac OS

gradle.properties, src/test/java/com/firebolt/FireboltDriverTest.java, src/test/java/com/firebolt/jdbc/metadata/FireboltDatabaseMetadataTest.java, src/test/java/com/firebolt/jdbc/util/VersionUtilTest.java
Bumped driver version to 3.3.0
=> chore: bump version to 3.3.0

src/integrationTest/java/integration/tests/SystemEngineTest.java
When running integration tests on GitHub actions there is one integration test that is failing. That can be reproduced locally.
There was a bug on the backend that required the test to have a workaround. That bug was fixed in staging so now we can remote the workaround from the test.
=>  (testfix) A bug was fixed on the backend so required changes in the tests

src/main/java/com/firebolt/jdbc/connection/FireboltConnectionProvider.java, src/main/java/com/firebolt/jdbc/connection/FireboltConnectionUserPassword.java, src/main/java/com/firebolt/jdbc/connection/LocalhostFireboltConnection.java, src/test/java/com/firebolt/jdbc/connection/FireboltConnectionProviderTest.java, src/test/java/com/firebolt/jdbc/connection/FireboltConnectionUserPasswordTest.java, src/test/java/com/firebolt/jdbc/connection/LocalhostFireboltConnectionTest.java
Addressed comments open on this review: https://github.com/firebolt-db/jdbc/pull/523
as I have closed the PR and then I saw the comments.
=> FIR-44260: addressed comments from previous review

src/integrationTest/java/integration/tests/PreparedStatementTest.java, src/main/java/com/firebolt/jdbc/type/JavaTypeToFireboltSQLString.java, src/main/java/com/firebolt/jdbc/type/date/SqlDateUtil.java, src/test/java/com/firebolt/jdbc/statement/preparedstatement/FireboltPreparedStatementTest.java
Created a patch that allows users to set LocalDate and LocalDateTime object values into PreparedStatements.
=> feat: FIR-44732 Support LocalDate and LocalDateTime in prepared statements

src/integrationTest/resources/statements/prepared-statement-struct/ddl.sql
Fixing set commands that enable struct.
=> test: Fix struct set commands in integration tests

src/main/java/com/firebolt/jdbc/cache/EncryptionService.java, src/main/java/com/firebolt/jdbc/cache/exception/EncryptionException.java, src/test/java/com/firebolt/jdbc/cache/EncryptionServiceTest.java
Added the class to encrypt and decrypt using AES/GCM algorithm. 
The encryption will be used in 2 places: to encrypt the file name and to encrypt the content of the file
The decryption will be used to decrypt the content of the file.
=> FIR-44260 added encryption service

.github/workflows/integration-test.yml
Fixed the integration run so we can trigger it manually independent of the nightlys.
=> Fix integration test run

src/main/java/com/firebolt/jdbc/cache/ConnectionCache.java, src/main/java/com/firebolt/jdbc/cache/FileService.java, src/main/java/com/firebolt/jdbc/cache/FilenameGenerator.java, src/main/java/com/firebolt/jdbc/cache/exception/ConnectionCacheDeserializationException.java, src/main/java/com/firebolt/jdbc/cache/exception/FilenameGenerationException.java, src/main/java/com/firebolt/jdbc/cache/key/CacheKey.java, src/main/java/com/firebolt/jdbc/cache/key/ClientSecretCacheKey.java, src/main/java/com/firebolt/jdbc/cache/key/LocalhostCacheKey.java, src/test/java/com/firebolt/jdbc/cache/FileServiceTest.java, src/test/java/com/firebolt/jdbc/cache/FilenameGeneratorTest.java, src/test/java/com/firebolt/jdbc/cache/InMemoryCacheServiceTest.java, src/test/java/com/firebolt/jdbc/cache/key/ClientSecretCacheKeyTest.java, src/test/java/com/firebolt/jdbc/cache/key/LocalhostCacheKeyTest.java, src/testCommon/java/com/firebolt/jdbc/testutils/TestFixtures.java
Added the FileService (knows how to interact with the files on disk: read, write, delete, etc)
Added the FIlenameGenerator that will take a cacheKey and generate the file name for it. 
Also added the encryption key for each of the CacheKey, so the CacheKey is responsible to provide the encryption key.
=> FIR-44260: added the file service and filename generator service

src/test/java/com/firebolt/jdbc/statement/FireboltStatementTest.java
I have seen this tests failing 3 times in the last 2 weeks. 
I am suspecting that the only way this can fail is if the query label has the text 123 in it (this explains why this only fails certain times as we log the query label).
I have changed the AWS_KEY id to something that is not going to be ever present in a UUID. Also stopped the appender after the test has finished.
=> Fixed the flaky statement test

src/integrationTest/java/integration/tests/datatype/BooleanTest.java
Added some variations of how we can insert true or false for a column using prepared statements. Also added negative test cases for the boolean values that are rejected.
=> test (noTicket) added some tests for boolean prepared statement

src/integrationTest/java/integration/tests/datatype/BigDecimalTest.java
When the bug FIR-48811 is resolved this test should be enabled.
=> (test) FIR-48811 - added a test that fails for bigint
