src/main/java/com/firebolt/jdbc/connection/FireboltConnection.java, src/test/java/com/firebolt/jdbc/connection/FireboltConnectionTest.java
Getting naming in line with other connectors as per https://docs.google.com/document/d/1HOnfyG0UHFnkZAhnkxfpfgjjSDkZm2eXkOact2BVuYo
=> fix: Renaming statistic tracking parameters

src/main/java/com/firebolt/jdbc/type/date/SqlDateUtil.java, src/test/java/com/firebolt/jdbc/type/date/SqlDateUtilTest.java
There is an edge case where Firebolt would send a date with a year 0000. Such date do no exist (but we get it from the backend). The purpose of this PR is to simply handle such scenario (as it currently throws an exception).
=> Handle edge case when year is 0000

build.gradle
When specifiying the jdbc as a dependency, the POM file states the existing dependencies, even though all of those are shaded, resulting in bigger packages. This commit removes all dependencies when the pom file is created.
=> Remove dependencies from pom.xml due to shading

src/main/java/com/firebolt/jdbc/resultset/compress/LZ4InputStream.java
FIR-22970: alb keep alive when `compress=1`
Previously when `compress=1`, we can receive a stream like the following (decimal), if it takes >3500sec for packdb to output anything:
```
32, -4, 102, -104, 79, -114, 2, 31, 97, -74, 79, 44, -19, 55, 15, 82, 48, -126, 35, 0, 0, 0, 24, 0, 0, 0, -16, 9, 115, 108, 101, 101, 112, 69, 97, 99, 104, 82, 111, 119, 40, 49, 41, 10, 98, 111, 111, 108, 101, 97, 110, 10, 27, 96, 48, 68, 104, 64, 75, -51, 28, 106, 28, 18, 101, 1, -4, 23, -126, 20, 0, 0, 0, 20, 0, 0, 0, 41, 102, 10, 2, 0, 80, 10, 102, 10, 102, 10
```
There can be several 32 in the beginning (our alb keep alive empty byte), and 16 bytes of checksum, and then 1 byte compression method byte (in case of LZ4, it is -126 or 0x82).
Since 32 can be part of the checksum, we dedicate 16 bytes of 0 to …
=> [FIR-22970] alb keep alive when compress=1

build.gradle
This is inspired by an old issue FIR-10166 that complains about the vulnerabilities in this library. The upgrade is done although this library was updated to pretty good version a year ago, but anyway it is good to keep all dependencies up-to-date.
=> FIR-10166 updated jackson version to the latest one 2.15.2

.github/workflows/release.yml
I think this might be preventing us from running release as hinted  in https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
=> ci: Use PAT for release action

src/main/java/com/firebolt/jdbc/connection/FireboltConnection.java, src/main/java/com/firebolt/jdbc/connection/settings/FireboltProperties.java, src/test/java/com/firebolt/jdbc/client/HttpClientConfigTest.java, src/test/java/com/firebolt/jdbc/client/query/StatementClientImplTest.java, src/test/java/com/firebolt/jdbc/connection/FireboltConnectionTest.java, src/test/java/com/firebolt/jdbc/connection/settings/FireboltPropertiesTest.java
The annoying factory method `of()` is removed. Now we have constructor that accepts `Properties` instead. Constructor can guarantee that all `final` members are initialised.
=> improved FireboltProperties: removed of() factory method, added constructors

build.gradle
Running `./gradlew build` produces a bunch of warning that report about missing javadoc. The default (?) policy requires javadoc on each public class/method/enum entry that is annoying. Meaning of some elements is obvious. For example `connect()` perform connection and `FireboltSessionProperty.DATABASE` is a property that holds database name. 
We do have some javadocs. Yes, some docs are missing. I will add documentation from time to time. But right now I'd want to suppress warnings about missing javadocs because I can miss other, more valuable warnings because of "missing javadoc" warnings.
=> Suppress no javadoc warning

src/main/java/com/firebolt/jdbc/service/FireboltGatewayUrlService.java, src/test/java/com/firebolt/jdbc/service/FireboltGatewayUrlServiceTest.java
System engine now comes without protocol in URL. We need to account for this in code.
=> fix: Add protocol to system engine

src/main/java/com/firebolt/jdbc/resultset/FireboltResultSet.java, src/main/java/com/firebolt/jdbc/service/FireboltStatementService.java, src/main/java/com/firebolt/jdbc/statement/FireboltStatement.java, src/test/java/com/firebolt/jdbc/connection/FireboltConnectionTest.java, src/test/java/com/firebolt/jdbc/resultset/FireboltResultSetTest.java, src/test/java/com/firebolt/jdbc/service/FireboltStatementServiceTest.java, src/test/java/com/firebolt/jdbc/statement/FireboltStatementTest.java, src/test/java/com/firebolt/jdbc/statement/preparedstatement/FireboltPreparedStatementTest.java
number of parameters is reduced because some of them can be retrieved from passed statement
(*) most of change here are in test mockup. The real change is in `FireboltStatementService.execute()` and in place where this method is called.
=> FIR-32353: refactored FireboltStatementService.execute()

build.gradle, src/integrationTest/java/integration/tests/PreparedStatementTest.java, src/main/java/com/firebolt/jdbc/connection/FireboltConnection.java, src/main/java/com/firebolt/jdbc/resultset/FireboltResultSet.java, src/main/java/com/firebolt/jdbc/statement/preparedstatement/FireboltPreparedStatement.java, src/main/java/com/firebolt/jdbc/util/InputStreamUtil.java, src/test/java/com/firebolt/jdbc/resultset/FireboltResultSetTest.java, src/test/java/com/firebolt/jdbc/statement/preparedstatement/FireboltPreparedStatementTest.java, src/test/java/com/firebolt/jdbc/util/InputStreamUtilTest.java
Blob, clob and stream related methods in prepared statement
=> FIR-32016, FIR-32018: implemented blob, clob, stream in PS

src/integrationTest/java/integration/tests/SystemEngineTest.java
The service account name now must end by alpha character
=> fix: FIR-33214: fixed service account name to follow new rules

build.gradle
Removed signing of a build artifact since we don't have a key now to sign with
=> build: remove signing of a build artifact

src/main/java/com/firebolt/jdbc/connection/FireboltConnection.java, src/test/java/com/firebolt/jdbc/connection/FireboltConnectionTest.java
Added auto_start_stop_control=ignore parameter to isValid call of JDBC connection
=> fix: Fir 35049 dont reset engine autostop with service queries in drivers for jdbc

src/main/java/com/firebolt/jdbc/statement/FireboltStatement.java, src/test/java/com/firebolt/jdbc/statement/FireboltStatementTest.java
Sanitizing logs to avoid printing secrets. Bumping down query printing to debug level instead.
Also fixed skipped tests.
=> fix(FIR-35270): Avoid printing secrets in logs

src/test/java/com/firebolt/jdbc/connection/FireboltConnectionTest.java
There were old settings set on URL for JDBC testing with localy running Firebolt instance. In order to remove these unused settings from Firebolt codebase - we need to clean them from here first.
=> Remove old/unused settings from FireboltConnectionTest

src/integrationTest/java/integration/ConnectionInfo.java, src/integrationTest/java/integration/IntegrationTest.java, src/integrationTest/java/integration/tests/ConnectionTest.java, src/main/java/com/firebolt/jdbc/connection/FireboltConnection.java, src/main/java/com/firebolt/jdbc/connection/settings/FireboltProperties.java, src/main/java/com/firebolt/jdbc/connection/settings/FireboltSessionProperty.java, src/test/java/com/firebolt/jdbc/connection/FireboltConnectionServiceSecretTest.java, src/test/java/com/firebolt/jdbc/connection/FireboltConnectionTest.java, src/test/java/com/firebolt/jdbc/connection/FireboltConnectionUserPasswordTest.java, src/test/java/com/firebolt/jdbc/connection/settings/FireboltPropertiesTest.java
Improvements for isValid method:
- FIR-37621 run validation for a system engine as well
- add a connection property `validate_on_system_engine`, which forces a connection to run isValid on a system engine even if it's connected to a user engine
=> Fir 37710 jdbc validate connection against system engine

.github/workflows/release.yml
Fixing release CI since PAT has expired and looks like we don't need it.
=> ci: Use GITHUB_TOKEN secret in release

src/test/java/com/firebolt/FireboltDriverTest.java, src/test/java/com/firebolt/jdbc/metadata/FireboltDatabaseMetadataTest.java, src/test/java/com/firebolt/jdbc/util/VersionUtilTest.java
Relaxing minor version check to avoid having to fix tests every time we do a version bump. We still check the methods are callable and return within reason (0 - 100).
=> test: relax version checks

.github/workflows/release.yml, gradle.properties
Eliminating the need to bump version manually, we only need to provide it on the action run.
Manual Maven release is still needed.
Verified changes during a dummy run (without maven publishing).
=> ci: Auto version bump and release

src/integrationTest/java/integration/tests/ConnectionTest.java, src/integrationTest/java/integration/tests/PreparedStatementTest.java, src/integrationTest/java/integration/tests/TimeoutTest.java, src/integrationTest/resources/statements/prepared-statement-struct/ddl.sql, src/main/java/com/firebolt/jdbc/connection/settings/FireboltProperties.java, src/main/java/com/firebolt/jdbc/connection/settings/FireboltSessionProperty.java, src/main/java/com/firebolt/jdbc/statement/FireboltStatement.java, src/main/java/com/firebolt/jdbc/statement/preparedstatement/FireboltPreparedStatement.java, src/test/java/com/firebolt/jdbc/connection/FireboltConnectionTest.java, src/test/java/com/firebolt/jdbc/connection/settings/FireboltPropertiesTest.java
Added `merge_prepared_statement_batches` parameter to JDBC. If will send all queries in a prepared statement batch as a single http request, separated by semicolon.
=> feat: FIR-43038 allow jdbc to send batch as a single multi statement

src/integrationTest/java/integration/tests/NumericTypesTest.java
Wrote this test to check the functionality. Decided to keep it in the codebase
=> test: large decimal

.github/workflows/release.yml
This fixes permissions issue when release action attempts to commit to the repo.
=> ci: Add PAT to release workflow

src/integrationTest/java/integration/tests/SystemEngineDatabaseMetaDataTest.java, src/main/java/com/firebolt/jdbc/metadata/FireboltDatabaseMetadata.java, src/test/java/com/firebolt/jdbc/metadata/FireboltDatabaseMetadataTest.java, src/test/resources/responses/metadata/firebolt-response-get-catalogs-example
Implemented the getCatalogs method from FireboltDatabaseMetadata to return all catalogs instead of just the one from the connection. Changed the existing unit test for this method and also created an integration test that checks that at least the current db provided for the integration tests is returned in the ResultSet (due to there being lots of databases available in staging)
=> feat(FIR-34063):implement get catalogs to return all dbs

src/integrationTest/java/integration/tests/StatementTest.java, src/main/java/com/firebolt/jdbc/client/FireboltClient.java, src/main/java/com/firebolt/jdbc/exception/ServerError.java, src/test/java/com/firebolt/jdbc/exception/ServerErrorTest.java
Updated ServerError creation to not trim the error message anymore, but to leave it complete. Now the error message is 1:1 with the one received from the server, so no more missing the line/column information
=> feat: FIR-44116 Line and Column information missing from JDBC errors

src/main/java/com/firebolt/jdbc/client/query/StatementClientImpl.java, src/test/java/com/firebolt/jdbc/client/query/StatementClientImplTest.java
This line was executed twice: 
QueryIdFetcher.getQueryFetcher(connection.getInfraVersion()).formatStatement(statementInfoWrapper);
One by itself and one to have the result assigned to a variable. Only keep one call. 
Also removed a commented line from tests.
=> feat: FIR-43922 - part2 - remove duplicate line

src/integrationTest/java/integration/IntegrationTest.java, src/integrationTest/java/integration/tests/ConnectionTest.java, src/integrationTest/java/integration/tests/StatementTest.java, src/main/java/com/firebolt/jdbc/client/query/StatementClientImpl.java, src/main/java/com/firebolt/jdbc/connection/FireboltConnection.java, src/test/java/com/firebolt/jdbc/connection/FireboltConnectionServiceSecretTest.java
Some API calls to the server return response headers that we need to set on the connection. 
When setting those connection properties, we are currently validating the connection by making a SELECT 1 statement call. (Same happens for reset call)
There are 2 problems:
1. we should trust the parameter headers that come from the server and should not do additional validation when setting the property
2. when we the server mentions that the connection needs to be reset we are clearing the properties and also validate the connection. The problem is that we do the SELECT 1 on the system engine url and not on the user engine url.
=> feat: FIR-44260 - do not validate connection when changing the paramters set from the server

src/integrationTest/java/integration/IntegrationTest.java, src/integrationTest/java/integration/tests/CachedConnectionTest.java, src/integrationTest/java/integration/tests/ConnectionTest.java, src/integrationTest/resources/statements/cached-connection/cleanup.sql, src/integrationTest/resources/statements/cached-connection/ddl.sql, src/main/java/com/firebolt/jdbc/client/query/StatementClient.java, src/main/java/com/firebolt/jdbc/service/FireboltEngineVersion2Service.java, src/test/java/com/firebolt/jdbc/connection/FireboltConnectionServiceSecretTest.java, src/test/java/com/firebolt/jdbc/service/FireboltEngineVersion2ServiceTest.java
Part2 
- cache the response for the use database and use engine calls
- for now we know what are the parameters that the server sends back so we keep those results in cache and update those values when we get the connection from cache. We also need to update the value for the endpoint after we do a use engine since next calls should use the user engine.
=> Fir 44260 reduce the number of requests during the connection establishing part2

src/main/java/com/firebolt/jdbc/connection/FireboltConnection.java, src/main/java/com/firebolt/jdbc/connection/FireboltConnectionServiceSecret.java, src/main/java/com/firebolt/jdbc/connection/FireboltConnectionUserPassword.java, src/main/java/com/firebolt/jdbc/connection/settings/FireboltProperties.java, src/main/java/com/firebolt/jdbc/connection/settings/FireboltSessionProperty.java, src/test/java/com/firebolt/jdbc/client/query/StatementClientImplTest.java, src/test/java/com/firebolt/jdbc/connection/FireboltConnectionServiceSecretTest.java, src/test/java/com/firebolt/jdbc/connection/FireboltConnectionUserPasswordTest.java, src/test/java/com/firebolt/jdbc/connection/LocalhostFireboltConnectionServiceTest.java, src/test/java/com/firebolt/jdbc/connection/settings/FireboltPropertiesTest.java
Add a new connection parameter: cache_connection
This will default to true for clientId/clientSecret connections (both for actual backend and when using localhost connections).
If the parameter is used on a username/password connection (Firebolt 1.0 backend) it will be ignored but a warning will be displayed to the user.
=> FIR-44620: add connection cache to url parameters

src/main/java/com/firebolt/jdbc/cache/CacheService.java, src/main/java/com/firebolt/jdbc/cache/CacheServiceProvider.java, src/main/java/com/firebolt/jdbc/cache/CacheType.java, src/main/java/com/firebolt/jdbc/cache/ConnectionCache.java, src/main/java/com/firebolt/jdbc/cache/DatabaseOptions.java, src/main/java/com/firebolt/jdbc/cache/EngineOptions.java, src/main/java/com/firebolt/jdbc/cache/InMemoryCacheService.java, src/main/java/com/firebolt/jdbc/cache/OnDiskMemoryCacheService.java, src/main/java/com/firebolt/jdbc/cache/exception/CacheException.java, src/main/java/com/firebolt/jdbc/cache/key/CacheKey.java, src/main/java/com/firebolt/jdbc/cache/key/ClientSecretCacheKey.java, src/main/java/com/firebolt/jdbc/cache/key/LocalhostCacheKey.java, src/main/java/com/firebolt/jdbc/connection/FireboltConnectionProvider.java, src/main/java/com/firebolt/jdbc/connection/FireboltConnectionServiceSecret.java, src/main/java/com/firebolt/jdbc/connection/LocalhostFireboltConnection.java, src/main/java/com/firebolt/jdbc/service/FireboltEngineVersion2Service.java, src/test/java/com/firebolt/jdbc/cache/CacheServiceProviderTest.java, src/test/java/com/firebolt/jdbc/cache/InMemoryCacheServiceTest.java, src/test/java/com/firebolt/jdbc/connection/FireboltConnectionProviderTest.java, src/test/java/com/firebolt/jdbc/connection/FireboltConnectionServiceSecretTest.java, src/test/java/com/firebolt/jdbc/connection/FireboltConnectionTest.java, src/test/java/com/firebolt/jdbc/connection/FireboltConnectionUserPasswordTest.java, src/test/java/com/firebolt/jdbc/connection/LocalhostFireboltConnectionTest.java, src/test/java/com/firebolt/jdbc/service/FireboltEngineVersion2ServiceTest.java
Cache the connection (only the in memory caching is provided in the review). The on disk cache will be sent as a separate review. 
CacheService will be created by the CacheProvider which will be a static instance. This means it will have the same cacheService across multiple invocations (a.k.a - multiple connections creations).
ConnectionCache is the object that will the object that will be stored in cache. When this object is created the first time we will store the connectionId of the connection that created it and saved it in cache. 
DatabaseOptions is a container for saving the database information for a database name. Currently we only save the db name but if more info will be needed in the future will be adding to this object.
EngineOptions is a container for saving engine …
=> feat: FIR-44260 add connection caching

src/integrationTest/java/integration/tests/client/UsageTrackingTest.java, src/main/java/com/firebolt/jdbc/cache/CacheServiceProvider.java, src/main/java/com/firebolt/jdbc/cache/CacheType.java, src/main/java/com/firebolt/jdbc/cache/ConnectionCache.java, src/main/java/com/firebolt/jdbc/cache/InMemoryCacheService.java, src/main/java/com/firebolt/jdbc/client/FireboltClient.java, src/main/java/com/firebolt/jdbc/connection/ConnectionIdGenerator.java, src/main/java/com/firebolt/jdbc/connection/FireboltConnection.java, src/main/java/com/firebolt/jdbc/connection/FireboltConnectionProvider.java, src/main/java/com/firebolt/jdbc/connection/FireboltConnectionServiceSecret.java, src/main/java/com/firebolt/jdbc/connection/FireboltConnectionUserPassword.java, src/main/java/com/firebolt/jdbc/connection/LocalhostFireboltConnection.java, src/test/java/com/firebolt/jdbc/cache/CacheServiceProviderTest.java, src/test/java/com/firebolt/jdbc/client/UsageTrackerUtilTest.java, src/test/java/com/firebolt/jdbc/client/UserAgentFormatter.java, src/test/java/com/firebolt/jdbc/client/query/StatementClientImplTest.java, src/test/java/com/firebolt/jdbc/connection/FireboltConnectionServiceSecretTest.java, src/test/java/com/firebolt/jdbc/connection/FireboltConnectionUserPasswordTest.java, src/test/java/com/firebolt/jdbc/connection/LocalhostFireboltConnectionTest.java
Adde connection information to the user-agent hearer:
- if connection is not cached and created the first time then only: connId:<xxx> will be added
- if the connection was using cached data then we add: connId:<abc>;cachedConnId:<yyy> where yyy is the connection id that tested the connection. 
Seems like integration tests are all using cached connections (which is a good thing) and they are passing:
=> feat: FIR-44260 add connection info to user agent header

build.gradle, src/integrationTest/java/integration/tests/PreparedStatementTest.java, src/main/java/com/firebolt/jdbc/type/BooleanTypeUtil.java, src/main/java/com/firebolt/jdbc/type/JavaTypeToFireboltSQLString.java, src/test/java/com/firebolt/jdbc/statement/preparedstatement/FireboltPreparedStatementTest.java, src/test/java/com/firebolt/jdbc/type/JavaTypeToFireboltSQLStringTest.java, src/testCommon/java/com/firebolt/jdbc/testutils/TestFixtures.java
Added a specialized class to handle all sorts of conversions from String, Numbers and Characters to Boolean.
Created tests for this method but in the current configuration of our transformer they do not work. 
We will need to update it to align ourself with the JDBC spec.
For the moment, setObject for a boolean outcome only work from a boolean object.
=> fix: FIR-44784 Fix boolean in prepared statements

src/integrationTest/java/integration/tests/CachedConnectionTest.java, src/integrationTest/java/integration/tests/ConnectionTest.java, src/integrationTest/java/integration/tests/StatementTest.java
Background:
I was trying to add a nightly job to run the tests on 11, 17 and 21 (all the long term supported java versions) and I had realized that Java 11 the tests were not compiling. 
The """ multi string line concept was added in Java 15. So had to sent this extra review to fix the tests to run on Java 11 (since that is how we are testing the driver that it works on Java 11 by running the integration tests"
=> test: Fixed the tests to compile with Java 11

src/integrationTest/java/integration/tests/AsyncQueryTest.java, src/integrationTest/java/integration/tests/CachedConnectionTest.java, src/integrationTest/resources/statements/async/cleanup.sql, src/integrationTest/resources/statements/async/ddl.sql, src/integrationTest/resources/statements/cached-connection/cleanup.sql, src/integrationTest/resources/statements/cached-connection/ddl.sql
Problem: when trying to setup nightly with different os name and java versions only one run was passing. 
When we have 3 os (windows, ubuntu, and macOS) and 3 java versions: 11, 17 and 21 the nightly job was creating 9 jobs to run integration tests. There jobs would run in parallel. 
Engine name and db names are unique for each run, but some tests were creating the same engine name in the ddl. 
Since these tests ran in parallel, the first run that succeeded would delete the engines (but at that point the ddl might have already run for the other runs so the test was assuming that the engine is present), until it was deleted. 
Create the engines in tests since we can get the engine name from the system property and append some values to it. This would guarantee that the engine names are …
=> test: fix the integration tests to run in parallel

.github/workflows/integration-test-v1.yml, .github/workflows/integration-test-v2.yml, .github/workflows/integration-test.yml, .github/workflows/nightly-v1.yaml, .github/workflows/nightly-v2.yaml
I have added the nightly jobs as part of its own review (I will take it out of the PR that dealt with the default temp directory).
I have added just one combination (java 11 and ubuntu). When running multiple combinations I see that the tests are randomly failing. I need to investigate why, but we will still get some benefits of running v1 and v2 nightly on java 11 on ubuntu meanwhile. 
Few notes:
- we don't have a runner for Mac (at least when I had the Mac in the os matrix, it did not seem to run)
- I had to add shell: bash to the scripts that were doing some checking since those were failing on windows. 
Next steps. I want to have it run on Java 17 and 21 and also on windows-latest. I need to check why they are failing though. 
In order to test it I had to modify the perf git hub …
=> ci: FIR-45195 add nighlty job to run v1 and v2 integration tests

build.gradle, src/main/java/com/firebolt/jdbc/cache/DirectoryPathResolver.java, src/test/java/com/firebolt/jdbc/cache/DirectoryPathResolverTest.java
Added the class that will resolve the default temp directory for writing cache files. 
We have to change some environment variables so I had to change the test setup. Since our tests are run in parallel, and we change the default temp directory some tests will fail since Mockito will try to run to the same temp directory. So when changing this class we need to run manually the tests in the DirectoryPathResolverTest (notice how the tests are disabled so they won't run In pipeline)
=> FID-44260 added class to resolve default temp directory

src/main/java/com/firebolt/jdbc/service/FireboltEngineVersion2Service.java
Instead of using @CustomLog I accidentally add the @Slf4j annotation which forces clients to have an LoggerFactory on the class path.
=> Fix the errors seen by sql cloud tests

src/integrationTest/java/integration/tests/client/TLSTest.java
On windows the TLS tests are failing with the following error
javax.net.ssl.SSLPeerUnverifiedException: Hostname localhost not verified:
certificate: sha256/yOowwRGffNWswtSf8MidkjubXGpM7kiG/amLJeRrOsw=
DN: CN=5e8635da-3d3d-4f80-8293-1e70661934d0
subjectAltNames: [127.0.0.1]
On Windows the resolution from localhost to 127.0.0.1 does not happen. So need to add both localhost and 127.0.0.1 as the subject alternative names for the cert.
=> (test) FIR-45231 - Fixed the TLS test that fails on windows

.github/workflows/integration-test-v1.yml, .github/workflows/integration-test-v2.yml
I have seen v1 scripts fail with the following error when running on Windows:
Task '.staging.firebolt.io' not found in root project 'firebolt-jdbc'.
On windows we need to pass in the env variables to Gradle in quotes. 
Windows run: https://github.com/firebolt-db/jdbc/actions/runs/14439806639 (it fails with  the timeout tests)
Ubuntu: https://github.com/firebolt-db/jdbc/actions/runs/14439813744
MacOs: https://github.com/firebolt-db/jdbc/actions/runs/14439817374/job/40487329231
=> test FIR-45277 fix the gradle script for windows v1 integration tests

.github/workflows/integration-test-v1.yml, .github/workflows/integration-test-v2.yml, src/integrationTest/java/integration/tests/TimeoutTest.java
The last test that is failing on nightly (both v1 and v2) is the timeout test. 
There are 2 types of failures for this test:
1. the query finishes sooner than 350 seconds (when it does it is around 340 seconds)
2. the query times out at 10 minutes (this is the test timeout)
I have created 2 variables for the jdbc repository (see screenshot) and pass those variables to the test script for v1 and v2 respectively. Changed the TimeoutTest to check these environment variables first and if not found to use the default ones from the test (We need to make sure we can still run the test from IntelliJ). I have used 1 at the end of the value to make sure we see it being read from the variable (see second screenshot for an example from a v1 run) 
I have also increased the timeout to 15 minutes. I …
=> (test) FIR-45277 pass in max series size from GitHub

src/main/java/com/firebolt/jdbc/connection/LocalhostFireboltConnection.java, src/test/java/com/firebolt/jdbc/connection/LocalhostFireboltConnectionTest.java
Account is not mandatory when connection to localhost (the usecase of packdb).
=> Allow localhost connection without account

.github/workflows/nightly-v1.yaml, .github/workflows/nightly-v2.yaml
I want to get the Nightly's run to pass successfully. Now they are failing on Windows and Java 11. 
For now exclude this combination from the nightly runs. 
I have created this jira to add this combo back: https://packboard.atlassian.net/browse/FIR-45378 (I am installing Windows in a Vm and try few things there to see if changing the registry configuration fixes the issue)
=> Exclude java 11 and windows from nightly runs

src/integrationTest/java/integration/IntegrationTest.java, src/integrationTest/java/integration/tests/ConnectionTest.java, src/integrationTest/java/integration/tests/StatementTest.java, src/integrationTest/java/integration/tests/SystemEngineTest.java, src/main/java/com/firebolt/jdbc/exception/ServerError.java, src/test/java/com/firebolt/jdbc/exception/ServerErrorTest.java
When a statement is executed from a client which is blocked / not allowed via network policy, the error message from the exception is null, due to the message being found via another key ("detail")
=> feat: FIR-38161 Fix unauthorized error message fetching in ServerError

src/integrationTest/java/integration/tests/CachedConnectionTest.java, src/testCommon/java/com/firebolt/jdbc/testutils/TestTag.java
We will be adding the firebolt core functionality soon. We would have tests that would run against firebolt-core. 
Define a class that would have all the test tags that can be used in test. Currently we have:
-v1
-v2
-slow
-common
-firebolt-core (added now)
In the future we can add more, and we will know which tags we have by looking at this class. If we agree on this I will use Cursor to do the refactoring to use the new tags. I only changed one test to make sure everything works fine.
=> (test) Defined the test tags that we can use

.github/workflows/release.yml
This was the flow that I wanted in the release action:
- run pre-release action (build, run integration tests, run smoke test)
- if the pre-release action is successful then bump the version and release the new version. 
In reality the bump-version and pre-release actions were running in parallel. 
Added the dependent action for the bump-version (so it will run only in case pre-release-testing is successful)
=> Do not run the bump version unless the pre-release is succcessful

src/integrationTest/java/integration/tests/CachedConnectionTest.java, src/integrationTest/resources/logback-test.xml
I am seeing on nightly runs the test that verifies the cache creation time failing. Fails 2/8 runs or 3/8 runs. Sometimes 0/8 runs. 
We delete the cache file and then we execute the statement to create the second db, second engine.
My theory is that the first test runs (and will execute statements against second engine which would have to start the engine). Then the tests takes about 1 minute (we do have 2 x 10 seconds waiting time). 
Start the second engine in the before all test. and also move the deletion of the test after the creation of the engine and db was executed.
=> Fix flaky test + enable debug for jdbc connection cache

.github/workflows/integration-test-v1.yml, .github/workflows/integration-test-v2.yml, src/testCommon/java/com/firebolt/jdbc/testutils/TestTag.java
Prepare to add the firebolt core integration tests. When running integration tests on cloud for v1 and v2 we need to exclude the core annotated tests (those will be for firebolt core).
=> (ci): FIR-44420 part1 - do not run core tests for cloud integration tests

.github/workflows/core-integration-test.yml, .github/workflows/integration-test-v2.yml, src/integrationTest/resources/core/config.json, src/integrationTest/resources/core/docker-compose.yaml
Added the workflow to run integration tests for Firebolt core. 
The workflow takes 3 parameters:
- docker image version (we can run arm or x86 docker images)
- operating system
- java version
We are starting with ubuntu, java 11 and the latest version of x86 of the firebolt core (that was released May 8th).
Once we have a stable firebolt version we could add nightly's job that would run against that version.
=> (ci) FIR-44420 part2 added the integration test workflow for core

.github/workflows/core-integration-test.yml, .github/workflows/integration-test-v1.yml, .github/workflows/integration-test-v2.yml, build.gradle, src/integrationTest/java/integration/CommonIntegrationTest.java, src/integrationTest/java/integration/GlobalSetupExtension.java, src/integrationTest/java/integration/IntegrationTest.java, src/integrationTest/java/integration/MockWebServerAwareIntegrationTest.java, src/integrationTest/java/integration/tests/AsyncQueryTest.java, src/integrationTest/java/integration/tests/ConnectionTest.java, src/integrationTest/java/integration/tests/DatabaseMetaDataTest.java, src/integrationTest/java/integration/tests/MissingDataTest.java, src/integrationTest/java/integration/tests/NullableValuesTest.java, src/integrationTest/java/integration/tests/NumericTypesTest.java, src/integrationTest/java/integration/tests/PreparedStatementArrayTest.java, src/integrationTest/java/integration/tests/PreparedStatementFbNumericTest.java, src/integrationTest/java/integration/tests/PreparedStatementTest.java, src/integrationTest/java/integration/tests/SpecialValuesTest.java, src/integrationTest/java/integration/tests/StatementCancelTest.java, src/integrationTest/java/integration/tests/StatementTest.java, src/integrationTest/java/integration/tests/SystemEngineDatabaseMetaDataTest.java, src/integrationTest/java/integration/tests/SystemEngineTest.java, src/integrationTest/java/integration/tests/TimeoutTest.java, src/integrationTest/java/integration/tests/TimestampTest.java, src/testCommon/java/com/firebolt/jdbc/testutils/TestTag.java
Before firebolt core we had 2 backend: v1 and v2 and we were controlling the tagging of the tests using the following tags:
- common (would run against both backends)
- v1 - would run only on v1
- v2 - would run only on v2
We used to run the integration tests for v1 by excluding the test with v2: -DexcludeTags=v2
This approach does not work when we add the core backend as well since now we have 7 possibilities instead of 3: 
- test should run against all backends
- test should run against just one backend (v1, v2 or core)
- tests should run on combination of backends (v1 and v2 but not on core, v1 and core but not v2, v2 and core but not v1)
Changed the tests to always specify the backends that the test should run against. Introduced another abstract class CommonIntegrationTest that can …
=> (test) FIR-44420 - include tests tags rather than exclude them when running integration tests

src/integrationTest/java/integration/tests/PreparedStatementTest.java, src/integrationTest/java/integration/tests/StatementTest.java, src/integrationTest/java/integration/tests/TimestampTest.java, src/integrationTest/resources/statements/prepared-statement-struct/ddl.sql
Core team has release the fixes in 4.22. Before it was 4.21.
They have fixed some issues with the setting of parameters not being recognized. 
There are few other changes as well:
- force_pgdate_timestampntz is not supported any more for core (actually it is not doing anything for cloud as well)
- time_zone setting is not supported for core but the new property is timezone. This is the same for cloud but it seems that on cloud both work. 
- error messages for an unknown parameter is different if the query is ran against user engine or system engine. So changed the tests to reflect that. For core it will be similar to cloud when running on user engine.
=> (test) FIR-44420 fixed the failing tests against 4.22

src/integrationTest/java/integration/tests/ConnectionTest.java, src/main/java/com/firebolt/jdbc/connection/FireboltConnection.java, src/main/java/com/firebolt/jdbc/connection/FireboltCoreConnection.java
During connection validation the driver sends a query parameter that is not supported to core: auto_start_stop_control
Core does not execute the query received if this parameter is set and returns this error instead:
`Error: Query failed with system error: Code: 1000006, e.displayText() = Changing auto_start_stop_control is not supported in Firebolt core, Stack trace (when copying this message, always include the lines below):`
We have already factored out the query parameter provider for v1, v2, dev and core. These are the parameters that will be sent to backend as part of the URI. The simple fix is to remove the unsupported parameter before sending it back to backend.
=> (fix) FIR-44420 testing if the connection is valid sends an unsupported query parameter to core

.github/workflows/release.yml
release workflow does not send the secrets for the firebolt core integration tests.
=> (ci) FIR-44420 Fixed release workflow

gradle.properties
When I released I used v.3.6.4 instead of v3.6.4 so that caused a wrong version number to be set on Git.
Revert the build bump so I can release again.
=> Revert wrong version number

.github/workflows/core-integration-test.yml, .github/workflows/integration-test-v1.yml, .github/workflows/integration-test-v2.yml, .github/workflows/nightly-core.yml, .github/workflows/nightly-v1.yaml, .github/workflows/nightly-v2.yaml
JDBC was the only one remaining from the drivers that did not have the slack integration for nightly in case of a failure. Add the slack integration for: v1, v2 and core nightlies.
Modify the underlying integration tests to accept a parameter to send notifications or not. When ran directly the default is false, when ran from the nightly it will pass in true for sending the slack notifications and also the slack token. Tests it for v2 with some failures and the messages get to slack.
=> (ci) FIR-46858 added the slack integration for nightly failures

.github/workflows/core-integration-test.yml
Detect when image is a non-root Core image
When the image is of the newer non-root type, pre-create an user-owned firebolt-data directory to prevent failure at startup.
=> fix(core): detect when image is a non-root Core image

src/main/java/com/firebolt/jdbc/connection/FireboltCoreConnection.java, src/test/java/com/firebolt/jdbc/connection/FireboltCoreConnectionTest.java
URL validation is pretty relaxed. It leaves certain things to the DNS resolver (like the length of the host name, or length of subdomain).
Initially we validated that the hostname is an IP address or FQDN (fully qualified domain name). That does not work well inside private networks were hostname like: cluster.local or firebolt-svc are valid hostnames. 
So relaxed the hostname validation to:
- max length of 253 chars
- max subdomain names to 63 chars
=> (bug) FIR-47675 - relax the hostname validation so core url will work inside Kubernetes cluster

build.gradle
Moved package release to Maven Portal, since OSSRH has reached end of life.
According to their docs (https://central.sonatype.org/pages/ossrh-eol/#logging-in-to-central-portal), we need to:
- update publishing links
- update repo credentials to Portal-ones (already update repository secrets)
=> build: FIR-47755 migrate release to maven portal

.github/workflows/release.yml, build.gradle, gradle.properties
Added a manual upload step for a package from Maven docs: 
https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/#ensuring-deployment-visibility-in-the-central-publisher-portal
=> Fir 47755 migrate jdbc publishing to maven central

.github/workflows/integration-test-v2.yml, build.gradle
When generating a test with a payload of 40 MB some times the runner fails and crashes: 
`Caused by: java.lang.OutOfMemoryError: Java heap space
at java.base/java.util.Arrays.copyOf(Arrays.java:3745)
at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:172)
at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:538)
at java.base/java.lang.StringBuilder.append(StringBuilder.java:179)
at com.firebolt.jdbc.statement.preparedstatement.FireboltPreparedStatement.asSingleStatement(FireboltPreparedStatement.java:292)
at com.firebolt.jdbc.statement.preparedstatement.FireboltPreparedStatement.executeBatch(FireboltPreparedStatement.java:276)
at integration.tests.ExceptionTypeTest.shouldThrowRequestBodyTooLargeExceptionForLargeData(Exce …
=>  ci (FIR-48710) Fixed flaky tests for exception type
